networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1123
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
